// <auto-generated />
namespace WorkAutomatorDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nonlocatedpipelineitemsandstoragecells2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonlocatedpipelineitemsandstoragecells2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105301448005_non-located-pipeline-items-and-storage-cells-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
