// <auto-generated />
namespace WorkAutomatorDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class storagecellspipeline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storagecellspipeline));
        
        string IMigrationMetadata.Id
        {
            get { return "202106012005121_storage-cells-pipeline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
