// <auto-generated />
namespace WorkAutomatorDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class namedescriptionforstoragecellprefab : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(namedescriptionforstoragecellprefab));
        
        string IMigrationMetadata.Id
        {
            get { return "202106052342494_name-description-for-storage-cell-prefab"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
