// <auto-generated />
namespace WorkAutomatorDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class companyisnotrequiredforuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companyisnotrequiredforuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202105181834447_company is not required for user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
